[package]
name = "bitbucket-task-bot"
version = "0.1.0"
authors = ["Hermann Czedik-Eysenberg <hermann.czedik-eysenberg@agfa.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.11"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1"
globset = "0.4"
toml = "1"
reqwest = { version = "0.13", features = ["json", "rustls"], default-features = false }
