[package]
name = "bitbucket-task-bot"
version = "0.1.0"
authors = ["Hermann Czedik-Eysenberg <hermann.czedik-eysenberg@agfa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
